/* ==========================================================================
   Les 7 pôles d'expertise — une page par pôle (référencement par expertise).
   seoTitle : 60 caractères max ; metaDesc : 150-160 caractères.
   ========================================================================== */
export const SERVICES = [
  {
    slug: 'immobilier-institutionnel',
    title: 'Immobilier institutionnel',
    short: 'Acquisitions, cessions et arbitrages d\'actifs pour les investisseurs, en asset deal comme en share deal.',
    color: '#1a2f66',
    img: 'tour-facade',
    imgAlt: 'Tour de bureaux à façade vitrée au crépuscule',
    kicker: 'Foncières · Assureurs · SCPI et OPCI · Fonds',
    seoTitle: 'Notaire en immobilier institutionnel à Paris',
    metaDesc: 'Notaires à Paris dédiés aux investisseurs institutionnels : acquisitions et cessions d\'actifs, share deals, BEFA, sale & leaseback et audits juridiques.',
    h1: 'Notaire en immobilier institutionnel à Paris',
    lead: 'Foncières, assureurs, fonds et SCPI nous confient l\'acquisition, l\'arbitrage et la structuration de leurs actifs tertiaires, logistiques, hôteliers et résidentiels.',
    intro: [
      'Une opération institutionnelle se joue sur des délais courts et des volumes importants. Notre pôle réunit des notaires et juristes habitués aux data rooms, aux négociations en anglais et aux calendriers de closing serrés.',
      'Nous intervenons en asset deal comme en share deal, en coordination avec les avocats, les conseils fiscaux, les banques et les asset managers, de la lettre d\'offre jusqu\'aux formalités postérieures.',
    ],
    missions: [
      'Acquisitions et cessions d\'immeubles de bureaux, commerces, logistique et hôtellerie',
      'Cessions de titres de sociétés à prépondérance immobilière (share deals)',
      'Bail en l\'état futur d\'achèvement (BEFA) et opérations de sale & leaseback',
      'Ventes de portefeuilles et de logements en bloc aux investisseurs',
      'Vente d\'immeuble à rénover (VIR) et restructurations lourdes',
      'Divisions en volumes, ensembles immobiliers complexes, ASL et AFUL',
      'Audits juridiques, data rooms et rapports de due diligence',
    ],
    clients: ['Foncières cotées et non cotées', 'Compagnies d\'assurance et mutuelles', 'SCPI, OPCI et fonds d\'investissement', 'Family offices', 'Asset managers'],
    steps: [
      ['Audit', 'Revue de la data room : titres de propriété, urbanisme, baux, servitudes, environnement. Rapport d\'audit et liste des points d\'attention.'],
      ['Négociation', 'Rédaction et négociation de la promesse, des garanties et des conditions suspensives avec les conseils de chaque partie.'],
      ['Closing', 'Organisation de la signature, y compris à distance, et flux de fonds sécurisés par la Caisse des Dépôts.'],
      ['Post-closing', 'Publicité foncière, mainlevées, remise des copies authentiques et bible de l\'opération.'],
    ],
    faqs: [
      ['Quelle différence entre asset deal et share deal ?', 'En asset deal, l\'immeuble est vendu directement : l\'acte est authentique et soumis aux droits de mutation immobiliers. En share deal, ce sont les titres de la société propriétaire qui sont cédés ; les droits d\'enregistrement sont calculés différemment et l\'audit porte aussi sur la société.'],
      ['Intervenez-vous dans les opérations en langue anglaise ?', 'Oui. Nos équipes négocient régulièrement en anglais et peuvent produire des traductions de travail des actes, l\'acte authentique restant rédigé en français.'],
      ['Combien de temps faut-il pour un closing ?', 'Il dépend de la purge des droits de préemption et des conditions suspensives. Une opération sans préemption peut être signée en quelques semaines après l\'accord sur le prix.'],
    ],
    refs: ['Art. 1582 et s. C. civ.', 'Art. L. 262-1 CCH (VIR)', 'Art. 726 CGI'],
    lead_partner: 'Me Hélène Duval',
    related: ['frais-de-notaire-2026', 'acte-authentique-electronique-signature-a-distance'],
  },
  {
    slug: 'construction-promotion-vefa',
    title: 'Construction et promotion',
    short: 'Programmes immobiliers en VEFA, du contrat de réservation à la livraison du dernier lot.',
    color: '#7a4a1e',
    img: 'chantier',
    imgAlt: 'Ensemble immobilier en cours de construction',
    kicker: 'Pôle Construction I · Promoteurs · VEFA',
    seoTitle: 'Notaire VEFA et promotion immobilière à Paris',
    metaDesc: 'Notaires spécialisés en VEFA à Paris : contrats de réservation, garantie financière d\'achèvement, règlements de copropriété et ventes en bloc.',
    h1: 'Notaire VEFA et promotion immobilière à Paris',
    lead: 'Nous accompagnons les promoteurs sur l\'ensemble de leurs programmes, du montage juridique à la livraison, et les acquéreurs qui achètent sur plan.',
    intro: [
      'La vente en l\'état futur d\'achèvement obéit à des règles protectrices précises : contrat de réservation, garantie financière, échéancier encadré, notification du projet d\'acte. Notre pôle sécurise chacune de ces étapes pour le promoteur comme pour l\'acquéreur.',
      'Nous préparons l\'ensemble des pièces du programme et gérons des volumes importants de signatures, en présentiel ou par acte authentique électronique à distance.',
    ],
    missions: [
      'Vente en l\'état futur d\'achèvement, en secteur protégé et en secteur libre',
      'Contrats de réservation et suivi des dépôts de garantie',
      'Vérification de la garantie financière d\'achèvement (GFA)',
      'États descriptifs de division et règlements de copropriété',
      'Dépôt des pièces du programme : notice descriptive, plans, permis',
      'Ventes en bloc aux bailleurs sociaux et aux investisseurs',
      'Suivi des appels de fonds et des livraisons',
    ],
    clients: ['Promoteurs nationaux et régionaux', 'Bailleurs sociaux', 'Investisseurs en bloc', 'Acquéreurs sur plan'],
    steps: [
      ['Montage', 'Analyse du foncier et des autorisations, rédaction de l\'état descriptif de division et du règlement de copropriété.'],
      ['Commercialisation', 'Modèles de contrats de réservation, dépôt de garantie plafonné à 5 % si la vente est signée dans l\'année.'],
      ['Signatures', 'Notification du projet d\'acte un mois avant la signature, puis signature de chaque lot.'],
      ['Livraison', 'Appels de fonds selon l\'avancement : 35 % aux fondations, 70 % hors d\'eau, 95 % à l\'achèvement.'],
    ],
    faqs: [
      ['Qu\'est-ce que la garantie financière d\'achèvement ?', 'C\'est une garantie, délivrée par une banque ou une compagnie d\'assurance, qui assure l\'achèvement de l\'immeuble si le promoteur fait défaut. Elle est obligatoire en VEFA dans le secteur protégé.'],
      ['Quel dépôt de garantie au contrat de réservation ?', 'Il est plafonné à 5 % du prix si la vente doit être signée dans l\'année, 2 % si elle intervient dans les deux ans. Au-delà de deux ans, aucun dépôt ne peut être exigé.'],
      ['Quand l\'acquéreur paie-t-il le prix ?', 'Au fur et à mesure de l\'avancement des travaux. Les appels de fonds ne peuvent dépasser 35 % à l\'achèvement des fondations, 70 % à la mise hors d\'eau et 95 % à l\'achèvement de l\'immeuble.'],
    ],
    refs: ['Art. 1601-3 C. civ.', 'Art. L. 261-10 et s. CCH', 'Art. R. 261-14 CCH'],
    lead_partner: 'Me Laurent Marchal',
    related: ['vefa-etapes-achat-sur-plan', 'frais-de-notaire-2026'],
  },
  {
    slug: 'amenagement-urbanisme',
    title: 'Aménagement et urbanisme',
    short: 'Maîtrise foncière, montages complexes et dissociation du foncier et du bâti.',
    color: '#0f4a3f',
    img: 'plan-masse',
    imgAlt: 'Vue aérienne d\'un plan masse d\'aménagement',
    kicker: 'Pôle Construction II · Aménageurs · Collectivités',
    seoTitle: 'Notaire en aménagement et urbanisme à Paris',
    metaDesc: 'Notaires à Paris pour les aménageurs et collectivités : maîtrise foncière, lotissements, ZAC, baux à construction, baux réels solidaires et volumes.',
    h1: 'Notaire en aménagement et urbanisme à Paris',
    lead: 'Aménageurs, collectivités et opérateurs fonciers s\'appuient sur notre pôle pour maîtriser le foncier et structurer des opérations mixtes.',
    intro: [
      'Les opérations d\'aménagement mêlent droit de l\'urbanisme, droit des biens et droit public. Nous intervenons en amont pour sécuriser la maîtrise foncière et choisir le montage adapté : vente, bail à construction, bail emphytéotique ou bail réel solidaire.',
      'Notre équipe rédige les cahiers des charges, les conventions et les divisions en volumes qui permettent de superposer logements, bureaux, commerces et équipements publics.',
    ],
    missions: [
      'Promesses sous condition d\'obtention d\'un permis purgé de tout recours',
      'Lotissements, permis d\'aménager et cahiers des charges',
      'ZAC, cahiers des charges de cession de terrain et projets urbains partenariaux',
      'Baux à construction, baux emphytéotiques et baux réels solidaires',
      'Organismes de foncier solidaire et accession sociale',
      'Divisions en volumes, servitudes et conventions de cour commune',
      'Cessions et acquisitions des collectivités territoriales',
    ],
    clients: ['Aménageurs publics et privés', 'Collectivités territoriales', 'Organismes de foncier solidaire', 'Établissements publics fonciers'],
    steps: [
      ['Diagnostic foncier', 'Analyse des titres, des servitudes et des règles d\'urbanisme applicables au périmètre.'],
      ['Montage', 'Choix de l\'outil : vente, bail à construction, bail emphytéotique, bail réel solidaire ou volumes.'],
      ['Contractualisation', 'Promesses sous conditions, cahiers des charges et conventions avec les opérateurs.'],
      ['Réalisation', 'Signature des actes de cession et suivi des purges et formalités.'],
    ],
    faqs: [
      ['Qu\'est-ce qu\'un bail réel solidaire ?', 'C\'est un bail de longue durée consenti par un organisme de foncier solidaire. Le ménage acquiert les droits sur le logement, l\'organisme conserve le terrain, ce qui réduit le prix d\'achat.'],
      ['Pourquoi recourir à une division en volumes ?', 'Elle permet de diviser un ensemble immobilier en fractions superposées dans l\'espace, sans parties communes. Elle convient aux opérations mixtes mêlant ouvrages publics et privés.'],
      ['Qu\'est-ce qu\'un permis purgé de tout recours ?', 'C\'est un permis qui ne peut plus être contesté par les tiers ni retiré par l\'administration. Les promesses sur des terrains à bâtir en font souvent une condition suspensive.'],
    ],
    refs: ['Art. L. 442-1 C. urb.', 'Art. L. 251-1 CCH', 'Art. L. 255-1 CCH'],
    lead_partner: 'Me Claire Fontaine',
    related: ['vefa-etapes-achat-sur-plan'],
  },
  {
    slug: 'vente-immobiliere',
    title: 'Vente immobilière',
    short: 'Achat et vente de logements, avant-contrats et actes du quotidien.',
    color: '#8a6a2a',
    img: 'acte-signature',
    imgAlt: 'Acte de vente signé à la plume sur un bureau de notaire',
    kicker: 'Actes courants · Particuliers · Primo-accédants',
    seoTitle: 'Notaire pour achat et vente immobilière à Paris',
    metaDesc: 'Acheter ou vendre un appartement à Paris : compromis, promesse de vente, délai de rétractation, frais de notaire. Un notaire dédié vous accompagne.',
    h1: 'Notaire pour votre achat ou votre vente immobilière à Paris',
    lead: 'Appartement, maison, terrain ou local : un notaire dédié vous accompagne de l\'avant-contrat à la remise des clés, avec un calendrier clair.',
    intro: [
      'Une vente immobilière suit un chemin précis. Nous vérifions la situation juridique du bien, préparons l\'avant-contrat, purgeons les droits de préemption et réunissons les pièces nécessaires à la signature.',
      'Vous suivez votre dossier en ligne, signez à l\'étude ou à distance, et recevez une estimation transparente des frais dès le premier rendez-vous.',
    ],
    missions: [
      'Promesses unilatérales et compromis de vente',
      'Ventes d\'appartements, de maisons, de terrains et de locaux',
      'Purge du droit de préemption urbain',
      'Contrôle du dossier de diagnostic technique et des pièces de copropriété',
      'Actes de prêt et mainlevées d\'hypothèque',
      'Servitudes, attestations de propriété et procurations',
      'Baux d\'habitation et baux commerciaux en la forme authentique',
    ],
    clients: ['Primo-accédants', 'Vendeurs et acquéreurs particuliers', 'Investisseurs locatifs', 'Entreprises et professions libérales'],
    steps: [
      ['Avant-contrat', 'Promesse ou compromis, après vérification du titre, du diagnostic technique et de la copropriété.'],
      ['Rétractation', 'L\'acquéreur dispose de 10 jours pour se rétracter à compter de la notification.'],
      ['Conditions', 'Obtention du prêt, purge du droit de préemption, états hypothécaires et urbanisme.'],
      ['Signature', 'Signature de l\'acte authentique, virement du prix et remise des clés, en moyenne trois mois après l\'avant-contrat.'],
    ],
    faqs: [
      ['Compromis ou promesse de vente : que choisir ?', 'Le compromis engage les deux parties. La promesse unilatérale engage le vendeur, l\'acquéreur disposant d\'une option qu\'il peut lever. Votre notaire vous conseille selon la situation.'],
      ['Combien coûtent les frais de notaire à Paris ?', 'Dans l\'ancien, comptez de 7 à 8 % du prix, dont la majeure partie correspond aux droits de mutation reversés à l\'État et aux collectivités. Notre simulateur vous donne une estimation détaillée.'],
      ['Puis-je choisir mon notaire si le vendeur a déjà le sien ?', 'Oui. Chaque partie peut choisir son notaire. Les émoluments sont alors partagés entre les notaires, sans surcoût pour vous.'],
    ],
    refs: ['Art. L. 271-1 CCH', 'Art. L. 213-2 C. urb.', 'Art. L. 721-2 CCH'],
    lead_partner: 'Me Julien Garnier',
    related: ['frais-de-notaire-2026', 'acte-authentique-electronique-signature-a-distance'],
  },
  {
    slug: 'financement-suretes',
    title: 'Financement et sûretés',
    short: 'Actes de prêt et sûretés réelles dotés de la force exécutoire.',
    color: '#3a1f4a',
    img: 'sceau',
    imgAlt: 'Sceau en laiton apposé sur un acte authentique',
    kicker: 'Banques · Établissements de crédit · Emprunteurs',
    seoTitle: 'Notaire financement, prêts et sûretés à Paris',
    metaDesc: 'Notaires à Paris pour les banques et emprunteurs : prêts hypothécaires, hypothèque légale du prêteur de deniers, cautionnements et fiducie-sûreté.',
    h1: 'Notaire en financement et sûretés à Paris',
    lead: 'Établissements bancaires et emprunteurs nous confient la rédaction et la sécurisation de leurs actes de prêt et de leurs garanties.',
    intro: [
      'L\'acte notarié offre au prêteur un avantage décisif : la copie exécutoire, qui permet de recouvrer la créance sans jugement préalable. Notre pôle rédige les actes de prêt et les sûretés réelles depuis la réforme du droit des sûretés de 2021.',
      'Nous travaillons avec les pools bancaires et les agents des sûretés sur les financements d\'acquisition, de promotion et de refinancement.',
    ],
    missions: [
      'Prêts hypothécaires et financements structurés',
      'Hypothèque légale spéciale du prêteur de deniers',
      'Hypothèques conventionnelles et affectations hypothécaires',
      'Cautionnements, nantissements de titres et fiducie-sûreté',
      'Crédits d\'accompagnement des promoteurs',
      'Copies exécutoires et titres exécutoires',
      'Mainlevées, renouvellements et radiations d\'inscriptions',
    ],
    clients: ['Banques et établissements de crédit', 'Pools bancaires et agents des sûretés', 'Promoteurs', 'Emprunteurs professionnels et particuliers'],
    steps: [
      ['Analyse', 'Revue de l\'offre de prêt, des garanties demandées et de la situation hypothécaire.'],
      ['Rédaction', 'Acte de prêt et sûretés, coordonnés avec l\'acte d\'acquisition le cas échéant.'],
      ['Signature', 'Signature, déblocage des fonds et inscription des sûretés.'],
      ['Suivi', 'Délivrance de la copie exécutoire, renouvellement et mainlevée en fin de prêt.'],
    ],
    faqs: [
      ['Qu\'est-ce que l\'hypothèque légale spéciale du prêteur de deniers ?', 'Elle a remplacé le privilège de prêteur de deniers depuis le 1er janvier 2022. Elle garantit le prêt qui finance l\'acquisition d\'un immeuble et prend rang à la date de l\'acte de vente.'],
      ['Pourquoi un prêt notarié ?', 'L\'acte notarié vaut titre exécutoire. En cas d\'impayé, le créancier peut engager une saisie sans obtenir préalablement un jugement.'],
      ['Combien coûte une mainlevée d\'hypothèque ?', 'Les émoluments sont fixés par le tarif réglementé et dépendent du montant de l\'inscription. Nous vous remettons un devis avant toute démarche.'],
    ],
    refs: ['Ord. n° 2021-1192', 'Art. 2393 et s. C. civ.', 'Art. L. 111-3 CPCE'],
    lead_partner: 'Me Antoine Leclerc',
    related: ['frais-de-notaire-2026'],
  },
  {
    slug: 'credit-bail-immobilier',
    title: 'Crédit-bail immobilier',
    short: 'Montage, cession et dénouement des contrats de crédit-bail.',
    color: '#0f4f5c',
    img: 'socle',
    imgAlt: 'Immeuble d\'activité au pied d\'une tour',
    kicker: 'Crédit-bailleurs · Entreprises · Pools',
    seoTitle: 'Notaire crédit-bail immobilier à Paris',
    metaDesc: 'Notaires spécialisés en crédit-bail immobilier à Paris : contrats, crédit-bail sur immeuble à construire, cessions de contrat et levée d\'option.',
    h1: 'Notaire en crédit-bail immobilier à Paris',
    lead: 'Crédit-bailleurs, pools et entreprises nous confient leurs contrats de crédit-bail immobilier, de la signature à la levée d\'option.',
    intro: [
      'Le crédit-bail immobilier permet à une entreprise de financer ses locaux professionnels : le crédit-bailleur acquiert l\'immeuble et le loue à l\'entreprise, qui peut en devenir propriétaire en levant l\'option d\'achat.',
      'Notre pôle intervient à chaque étape : acquisition par le crédit-bailleur, contrat, avenants, cession du contrat, levée d\'option anticipée ou à terme.',
    ],
    missions: [
      'Contrats de crédit-bail immobilier et acquisition par le crédit-bailleur',
      'Crédit-bail sur immeuble à construire et en VEFA',
      'Cession-bail (lease-back)',
      'Levée d\'option anticipée ou à terme',
      'Cessions de contrats et substitutions de crédit-preneur',
      'Montages en pool et conventions entre crédit-bailleurs',
      'Publicité foncière des contrats de plus de douze ans',
    ],
    clients: ['Sociétés de crédit-bail', 'Pools de crédit-bailleurs', 'PME et ETI', 'Groupes industriels et logistiques'],
    steps: [
      ['Acquisition', 'Le crédit-bailleur acquiert le terrain ou l\'immeuble, éventuellement en VEFA.'],
      ['Contrat', 'Rédaction du contrat : durée, loyers, option d\'achat, charges et assurances.'],
      ['Vie du contrat', 'Avenants, cessions de contrat, sous-location et travaux.'],
      ['Levée d\'option', 'Acte de vente au crédit-preneur et formalités de publicité foncière.'],
    ],
    faqs: [
      ['Qu\'est-ce que la levée d\'option ?', 'C\'est l\'exercice par le crédit-preneur de la promesse de vente stipulée au contrat. Elle entraîne le transfert de propriété de l\'immeuble moyennant le prix convenu.'],
      ['Le contrat doit-il être publié ?', 'Oui, lorsqu\'il est conclu pour plus de douze ans, ce qui est le cas de la plupart des crédits-baux immobiliers. La publication le rend opposable aux tiers.'],
      ['Peut-on céder un contrat de crédit-bail ?', 'Oui, avec l\'accord du crédit-bailleur. La cession est fréquente lors de la vente d\'un fonds ou d\'une restructuration de groupe.'],
    ],
    refs: ['Art. L. 313-7 CMF', 'Art. 239 sexies CGI', 'Décret n° 55-22, art. 28'],
    lead_partner: 'Me Sophie Bertrand',
    related: ['credit-bail-immobilier-levee-option'],
  },
  {
    slug: 'famille-patrimoine-succession',
    title: 'Famille, patrimoine et succession',
    short: 'Organiser, protéger et transmettre, à chaque étape de la vie.',
    color: '#5c1a2b',
    img: 'minutier',
    imgAlt: 'Registres reliés de cuir dans une bibliothèque d\'archives notariales',
    kicker: 'Couples · Familles · Chefs d\'entreprise',
    seoTitle: 'Notaire succession, donation et famille à Paris',
    metaDesc: 'Notaires à Paris pour vos successions, donations, contrats de mariage, PACS et testaments. Conseil patrimonial et transmission d\'entreprise.',
    h1: 'Notaire en droit de la famille, donation et succession à Paris',
    lead: 'Contrat de mariage, donation, testament, succession : nous vous conseillons pour protéger vos proches et transmettre votre patrimoine dans les meilleures conditions.',
    intro: [
      'Chaque situation familiale est singulière. Nous prenons le temps de comprendre la vôtre pour proposer les outils adaptés : régime matrimonial, donation-partage, démembrement de propriété, testament ou mandat de protection future.',
      'Lors d\'un décès, nous accompagnons les héritiers dans toutes les étapes du règlement de la succession, de l\'acte de notoriété à la déclaration fiscale.',
    ],
    missions: [
      'Contrats de mariage, changements de régime matrimonial et PACS',
      'Donations, donations-partages et donations entre époux',
      'Testaments authentiques et inscription au fichier central',
      'Règlement des successions et déclarations de succession',
      'Divorce par consentement mutuel : dépôt de la convention',
      'Mandat de protection future et protection des personnes vulnérables',
      'Démembrement de propriété, SCI familiales et transmission d\'entreprise',
    ],
    clients: ['Couples mariés, pacsés ou en concubinage', 'Familles recomposées', 'Héritiers', 'Chefs d\'entreprise et familles entrepreneuriales'],
    steps: [
      ['Écoute', 'Un premier rendez-vous pour comprendre votre situation et vos objectifs.'],
      ['Bilan', 'Analyse de votre patrimoine et des conséquences civiles et fiscales de chaque option.'],
      ['Solution', 'Rédaction des actes : contrat de mariage, donation, testament, mandat.'],
      ['Suivi', 'Mise à jour de votre stratégie au fil des évènements de la vie.'],
    ],
    faqs: [
      ['Dans quel délai déposer la déclaration de succession ?', 'Dans les six mois du décès lorsqu\'il survient en France métropolitaine, douze mois dans les autres cas. Passé ce délai, des intérêts de retard sont dus.'],
      ['Combien puis-je donner à mes enfants sans droits ?', 'Chaque parent peut donner 100 000 € par enfant tous les quinze ans en franchise de droits, auxquels peuvent s\'ajouter d\'autres abattements selon les cas.'],
      ['Faut-il passer chez le notaire pour un testament ?', 'Ce n\'est pas obligatoire, mais le testament authentique est difficilement contestable et tout testament confié au notaire est inscrit au fichier central, ce qui garantit qu\'il sera retrouvé.'],
    ],
    refs: ['Art. 1397 C. civ.', 'Art. 229-1 C. civ.', 'Art. 779 CGI'],
    lead_partner: 'Me Isabelle Rousseau',
    related: ['donation-abattements-2026', 'succession-delais'],
  },
];
